services:
  dask-scheduler:
    image: daskdev/dask:latest
    container_name: dask-scheduler
    ports:
      - "8786:8786"     # puerto para comunicación con workers y clientes
      - "8787:8787"     # dashboard web
    command: dask-scheduler
    env_file:
      - .env
    networks:
      - dask-net
    deploy:
      resources:
        limits:
          cpus: '0.1'         # Muy bajo porque solo coordina, no computa
          memory: 1g
    cpuset: "1"              # Asignar CPU 1 para scheduler

  dask-worker-1:
    image: daskdev/dask:latest
    depends_on:
      - dask-scheduler
    environment:
      - EXTRA_APT_PACKAGES=vim
    command: dask-worker tcp://dask-scheduler:8786 --nthreads 1 --memory-limit 2GB
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g
    cpuset: "0"              # Asignar CPU 0 para worker 1
    container_name: dask-worker-1
    networks:
      - dask-net

  dask-worker-2:
    image: daskdev/dask:latest
    depends_on:
      - dask-scheduler
    environment:
      - EXTRA_APT_PACKAGES=vim
    command: dask-worker tcp://dask-scheduler:8786 --nthreads 1 --memory-limit 2GB
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g
    cpuset: "1"
    container_name: dask-worker-2
    networks:
      - dask-net

  dask-worker-3:
    image: daskdev/dask:latest
    depends_on:
      - dask-scheduler
    environment:
      - EXTRA_APT_PACKAGES=vim
    command: dask-worker tcp://dask-scheduler:8786 --nthreads 1 --memory-limit 2GB
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g
    cpuset: "0"
    container_name: dask-worker-3
    networks:
      - dask-net

networks:
  dask-net:
    driver: bridge
