version: "3.8"

services:
  dask-scheduler:
    image: daskdev/dask:latest
    container_name: dask-scheduler
    ports:
      - "8786:8786"     # puerto para la comunicación con workers y clientes
      - "8787:8787"     # dashboard web
    command: dask-scheduler
    env_file:
      - .env
    networks:
      - dask-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g

  dask-worker:
    image: daskdev/dask:latest
    depends_on:
      - dask-scheduler
    environment:
      - EXTRA_APT_PACKAGES=vim
    command: dask-worker tcp://dask-scheduler:8786 --nthreads 2 --memory-limit 2GB
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: ${NUM_WORKERS}   # aquí defines cuántos workers
      resources:
        limits:
          cpus: '1'
          memory: 2g
    networks:
      - dask-net

networks:
  dask-net:
    driver: bridge
